language: python

sudo: required
dist: trusty

env:
  - OS_TYPE=debian8
  - OS_TYPE=debian9
  - OS_TYPE=ubuntu16.04

services:
  - docker

python:
  - "2.7"


before_install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - xhost +local:root
  - docker build -t ndts .travis/${OS_TYPE}
  - docker run  --name  ndts -d -it -v `pwd`:/home/tango -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e DISPLAY=$DISPLAY   ndts
  - .travis/install.sh ${OS_TYPE}

script:
  - .travis/run.sh

after-script:
  - docker stop ndts
  - docker rm ndts
