#!/usr/bin/env python
#   This file is part of nexdatas - Tango Server for NeXus data writer
#
#    Copyright (C) 2012-2013 DESY, Jan Kotanski <jkotan@mail.desy.de>
#
#    nexdatas is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    nexdatas is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with nexdatas.  If not, see <http://www.gnu.org/licenses/>.
## \package nxsconfigtool nexdatas
## \file nxscomp_designer.pyw
# GUI to create the XML components 

""" NXS Component Designer - configuration tool for Nexus Data Writer """

import logging
import sys
from optparse import OptionParser

from PyQt4.QtGui import (QApplication, QIcon)


from nxsconfigtool.MainWindow import MainWindow
from nxsconfigtool.qrc import qrc_resources
from nxsconfigtool import __version__


## the main function
def main():
    levels = {'debug': logging.DEBUG,
              'info': logging.INFO,
              'warning': logging.WARNING,
              'error': logging.ERROR,
              'critical': logging.CRITICAL}

    usage = "usage: nxscomp_designer.pyw "\
        "[-s server] [-c components] [-d datasources] ... "

    parser = OptionParser(usage=usage)

    parser.add_option(
        "-m", "--mandatory",  
        action="store_true",
        default=False, dest="mandatory", 
        help="make use mandatory components as well")
    parser.add_option(
        "-v","--version", 
        action="store_true",
        default="False",
        dest="version", 
        help="program version")
    parser.add_option(
        "-s","--server", dest="server", 
        help="configuration server")
    parser.add_option(
        "-c","--components", dest="components", 
        help="directory with components")
    parser.add_option(
        "-d","--datasources", dest="datasources", 
        help="directory with datasources")
    parser.add_option(
        "-l","--log", dest="log", 
        help="logging level, i.e. debug, info, warning, error, critical")

    (options, _) = parser.parse_args()


    if options.log:
        level_name = options.log
        level = levels.get(level_name, logging.NOTSET)
        logging.basicConfig(level=level)     

    if options.version:
        level_name = 1
        level = levels.get(level_name, logging.NOTSET)
        logging.basicConfig(level=level)     
        logger = logging.getLogger("")
        logger.info(__version__)
        sys.exit(0)

#    import gc
#    gc.set_debug(gc.DEBUG_LEAK | gc.DEBUG_STATS)
#    gc.set_debug(gc.DEBUG_LEAK )
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon(":/icon.png"))
    app.setOrganizationName("DESY")
    app.setOrganizationDomain("desy.de")
    app.setApplicationName("NXS Component Designer")
    form = MainWindow(options.components, options.datasources, options.server)
    form.show()

    sys.exit(app.exec_())



if __name__ == "__main__":
    main()


